apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-iis-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: CPD IBM Information Server
  image: icr.io/cpopen/ibm-cpd-iis-operator-catalog@sha256:cc9d327a0bd8a7701ae10eee05809faacb89a66b88fc62dc5c4c056f7d8e8613
  publisher: IBM
  sourceType: grpc
