apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2aaservice-cp4d-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Db2aaservice CP4D Catalog
  image: icr.io/cpopen/ibm-db2aaservice-cp4d-operator-catalog@sha256:3e7aa80ebead2c5bee35e60bbb10b74f56a1a4a1ad85c13baccd171053c36b80
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m