apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-datarefinery-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: Cloud Pak for Data IBM DataRefinery
  image: icr.io/cpopen/ibm-cpd-datarefinery-operator-catalog@sha256:1be8af2b5940f1ecc59aa7c5015f8d3783a59b271c76a053d83df8c5f4779e60
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
