apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-scheduling-catalog
  namespace: openshift-marketplace
  annotations:
    buildversion: "1.3.6+20220606.001060.efdb112"
spec:
  displayName: IBM Cloud Pak for Data Scheduler Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-scheduler-operator-catalog@sha256:ce488fd90135d87cb6c9aa4ba443278f0c6e6eb5b743c9265d5fd13a4016dce3
  updateStrategy:
    registryPoll:
      interval: 45m
