apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-dv-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Data Virtualization
  image: icr.io/cpopen/ibm-cpd-dv-operator-catalog@sha256:1aa67a4b3b8aa3fc124a5f2b45c69cda8ce819bdabf2e75cd073303777b51f0c
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m