apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fdb-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM FoundationDB
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/fdb-operator-catalog@sha256:00ab5fb76fa51688ba0e31dabc5220e4f0cd18d630a2c87c48058f2c1ff698da