apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-datastage-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM CPD DataStage
  image: icr.io/cpopen/ds-ent-operator-catalog@sha256:5535ea4f089e17fac051ba5d6772137874780e341fd946e65e2aaf9935f37e10
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
