apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: manta-adl-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: MANTA Operator Catalog
  image: icr.io/cpopen/manta-adl-operator-catalog@sha256:8d616eb6ef3f20c8441c71cac22431e7ff9f0d35f5332fb74d74d392418cc219
  publisher: MANTA Software
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
